version: 0.2
phases:
    build:
        commands:
            - echo "S3 Upload to $DEPLOY_BUCKET is beginning"
            - aws s3 sync . s3://$DEPLOY_BUCKET/ --delete --exclude "*" --include "*.json" --include "*.yml"
            - echo "S3 Upload Complete, updating cloudformation now..."
            - chmod +x codepipeline/run-sc-deploy.sh
            - /bin/bash codepipeline/run-sc-deploy.sh
            # - /bin/bash codepipeline/run-pipelineupdate.sh
            # - /bin/bash codepipeline/run-cloudformationupdate.sh

    post_build:
        commands:
            - echo "Deploy complete"
