version: 0.2
phases:
    build:
        commands:
            - echo "S3 Upload to $DEPLOY_BUCKET is beginning"
            - aws s3 sync . s3://$DEPLOY_BUCKET/ --delete --exclude "*" --include "*.json" --include "*.yml"
            - echo "S3 Upload Complete, updating cloudformation now..."
            # - /bin/bash codepipeline/run-pipelineupdate.sh
            # - /bin/bash codepipeline/run-cloudformationupdate.sh
            - aws cloudformation update-stack --stack-name SC-DEV-Portfolio --template-url  "https://$DEPLOY_BUCKET.s3.amazonaws.com/templates/dev-portfolio/sc-dev-portfolio.yml" --parameters "[{\"UsePreviousValue\":\"true\"}]" --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
            - aws cloudformation update-stack --stack-name SC-DEV-EC2-Product --template-url  "https://$DEPLOY_BUCKET.s3.amazonaws.com/templates/devenv/ec2/sc-ec2-linux-ra.json" --parameters "[{\"UsePreviousValue\":\"true\"}]" --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
            - aws cloudformation update-stack --stack-name SC-DEV-VPC-Product --template-url  "https://$DEPLOY_BUCKET.s3.amazonaws.com/templates/devenv/ec2/sc-vpc-ra.json" --parameters "[{\"UsePreviousValue\":\"true\"}]" --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
            - aws cloudformation update-stack --stack-name SC-DEV-MYSQL-Product --template-url  "https://$DEPLOY_BUCKET.s3.amazonaws.com/templates/devenv/ec2/sc-mysql-ra.json" --parameters "[{\"UsePreviousValue\":\"true\"}]" --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
            - aws cloudformation wait stack-update-complete --stack-name SC_DEV_Portfolio
            - aws cloudformation wait stack-update-complete --stack-name SC-DEV-EC2-Product
            - aws cloudformation wait stack-update-complete --stack-name SC-DEV-VPC-Product
            - aws cloudformation wait stack-update-complete --stack-name SC-DEV-MYSQL-Product

    post_build:
        commands:
            - echo "Deploy complete"
